// <auto-generated />
using System;
using BakeryStock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BakeryStock.Migrations
{
    [DbContext(typeof(BakeryStockContext))]
    [Migration("20230814200009_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BakeryStock.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Fornecedor")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("Preço")
                        .HasColumnType("real");

                    b.Property<DateTime?>("Validade")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("BakeryStock.Models.ProdutoTabela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Produto_IDId")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int?>("Tabela_IDId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Produto_IDId");

                    b.HasIndex("Tabela_IDId");

                    b.ToTable("ProdutoTabelas");
                });

            modelBuilder.Entity("BakeryStock.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Produto_IDId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int?>("Tabela_IDId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Produto_IDId");

                    b.HasIndex("Tabela_IDId");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("BakeryStock.Models.Tabela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tabelas");
                });

            modelBuilder.Entity("ProdutoTabela", b =>
                {
                    b.Property<int>("ProdutosId")
                        .HasColumnType("integer");

                    b.Property<int>("TabelasId")
                        .HasColumnType("integer");

                    b.HasKey("ProdutosId", "TabelasId");

                    b.HasIndex("TabelasId");

                    b.ToTable("ProdutoTabela");
                });

            modelBuilder.Entity("BakeryStock.Models.ProdutoTabela", b =>
                {
                    b.HasOne("BakeryStock.Models.Produto", "Produto_ID")
                        .WithMany()
                        .HasForeignKey("Produto_IDId");

                    b.HasOne("BakeryStock.Models.Tabela", "Tabela_ID")
                        .WithMany()
                        .HasForeignKey("Tabela_IDId");

                    b.Navigation("Produto_ID");

                    b.Navigation("Tabela_ID");
                });

            modelBuilder.Entity("BakeryStock.Models.Registro", b =>
                {
                    b.HasOne("BakeryStock.Models.Produto", "Produto_ID")
                        .WithMany()
                        .HasForeignKey("Produto_IDId");

                    b.HasOne("BakeryStock.Models.Tabela", "Tabela_ID")
                        .WithMany()
                        .HasForeignKey("Tabela_IDId");

                    b.Navigation("Produto_ID");

                    b.Navigation("Tabela_ID");
                });

            modelBuilder.Entity("ProdutoTabela", b =>
                {
                    b.HasOne("BakeryStock.Models.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakeryStock.Models.Tabela", null)
                        .WithMany()
                        .HasForeignKey("TabelasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
